name: Deploy to Google Cloud Functions
on: [push]
jobs:
  deploy:
    name: GCP Authenticate
    runs-on: ubuntu-latest
    steps:
    - name: Current Time
      run: date

    # https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions
    # If you don't use the actions/checkout action, the directory will be empty. For example, /home/runner/work/my-repo-name/my-repo-name.
    - name: Repo Checkout to Master
      uses: actions/checkout@v1

    - name: Setup Google Cloud
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: ${{ secrets.ProjectID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
      with:
        args: info
        
    - name: List Files
      run: "ls -la"

    - name: Set Default ProjectID
      run: |
        gcloud config set project ${{ secrets.ProjectID }}

    - name: Setup Google Cloud Deploy Key
      run: |
        echo ${{ secrets.GCLOUD_AUTH }} | base64 -d > deploy-key.json
        gcloud auth activate-service-account --key-file ./deploy-key.json

    - name: GCP Functions List
      run: |
        gcloud functions list

    - name: Setup Env
      run: |
        echo "PROJECT_ID: ${{  secrets.ProjectID }}" >> .env
        ls -la .env

    - name: Deploy to GCP
      run: |
        cd upload
        go mod vendor
        cd ..
        gcloud functions deploy link --source=link --entry-point=Link --runtime=go113 --trigger-http --quiet --env-vars-file .env
        gcloud alpha functions add-iam-policy-binding link --member=allUsers --role=roles/cloudfunctions.invoker

