name: GoogleCloudFuncitons
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.11
      uses: actions/setup-go@v1
      with:
        go-version: 1.11
      id: go

  GCP Authenticate:
    name: GCP Authenticate
    runs-on: ubuntu-latest
    steps:
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

  GCP Cli:
    name: GCP Cli
    runs-on: ubuntu-latest
    needs: GCP Authenticate
    steps:
    - name: GCP List Clusters
      uses: actions/gcloud/cli@master
      with:
        args: "functions list"

    - name: GCP List Clusters
      uses: actions/gcloud/cli@master
      with:
        args: "functions deploy link --entry-point=Link --runtime=go111 --trigger-http"
