name: GoogleCloudFuncitons
on: [push]
jobs:
  deploy:
    name: GCP Authenticate
    runs-on: ubuntu-latest
    steps:
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        # https://github.com/actions/gcloud/issues/13#issuecomment-511596628
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

    - name: GCP Setup Project ID
      uses: actions/gcloud/cli@master
      with:
        args: "config set project ${{ secrets.ProjectID }}"

    - name: GCP Functions List
      uses: actions/gcloud/cli@master
      with:
        args: "functions list"

    - name: PWD
      run: "pwd"

    - name: File List
      run: "ls -la"

    - name: Upper File List
      run: "ls -la .."

    # https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions
    # If you don't use the actions/checkout action, the directory will be empty. For example, /home/runner/work/my-repo-name/my-repo-name.
    - name: Repo Checkout
      uses: actions/checkout@master

    - name: PWD
      run: "pwd"

    - name: File List
      run: "ls -la"

    - name: Upper File List
      run: "ls -la .."

    - name: Deploy to GCP
      uses: actions/gcloud/cli@master
      with:
        args: "functions deploy link --entry-point=Link --runtime=go111 --trigger-http --source=."
